name = "GridapPETSc"
uuid = "bcdc36c2-0c3e-11ea-095a-c9dadae499f1"
authors = ["Francesc Verdugo <fverdugo@cimne.upc.edu>", "VÃ­ctor Sande <vsande@cimne.upc.edu>", "Alberto F. Martin <alberto.martin@monash.edu>"]
version = "0.5.2"

[deps]
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapDistributed = "f9701e48-63b3-45aa-9a63-9bc6c271f355"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
PETSc_jll = "8fa3689e-f0b9-5420-9873-adf6ccf46f2d"
PartitionedArrays = "5a9dfac6-5c52-46f7-8278-5e2210713be9"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseMatricesCSR = "a0a7dd2c-ebf4-11e9-1f05-cf50bc540ca1"

[compat]
Gridap = "0.17, 0.18"
GridapDistributed = "0.3, 0.4"
MPI = "0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20"
PETSc_jll = "=3.13.4, =3.15.2"
PartitionedArrays = "0.3"
SparseMatricesCSR = "0.6.6"
julia = "1.3"

[extras]
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
