name = "GridapPETSc"
uuid = "bcdc36c2-0c3e-11ea-095a-c9dadae499f1"
authors = ["VÃ­ctor Sande <vsande@cimne.upc.edu>"]
version = "0.2.1"

[deps]
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Gridap = "0.8.0, 0.9.0, 0.10, 0.11, 0.13"
MPI = "0.10.1, 0.13.1, < 0.14.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
